language: java
jdk:
  - oraclejdk8
dist: trusty
node_js:
  - '15'
services:
  - mongodb

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - pyenv global system 3.6
  - pip3 install --user codecov
  - nvm install 15.6.0
  - mongo --version
  - npm install -g yarn
  - yarn install
install:
  - cd myconext-gui && yarn install && cd ..
  - cd account-gui && yarn install && cd ..
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
  - cd myconext-gui && yarn build && yarn test && cd ..
  - cd account-gui && yarn build && yarn test && cd ..
after_success:
  - codecov
