logging:
  level:
    org.springframework.data.mongodb: INFO
    org.springframework.security: INFO

server:
  port: 8081

email:
  from: test@openconext.org
  base-url: http://localhost:8081

cron:
  node-cron-job-responsible: true

mongodb_db: surf_id_test

base_path: http://localhost:8081
redirect_url: http://localhost:3000
sp_entity_id: https://engine.test.surfconext.nl/authentication/sp/metadata

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/${mongodb_db}
  mail:
    host: localhost
    port: 3025

management:
  health:
    mail:
      enabled: false
