server:
  port: 8088
  error:
    whitelabel:
      enabled: false

environment: local
mongodb_db: surf_id_test
# This must be same secret used in the TiqrController
encryption_secret: "secret"
eduid:
  base_url: "http://localhost:8081"

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/${mongodb_db}
      auto-index-creation: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: "/internal"
  endpoint:
    info:
      enabled: true
  info:
    git:
      mode: full

