logging:
  config: classpath:logback.xml
  level:
    org.springframework.data.mongodb: INFO
    org.springframework.data.convert: INFO
    org.springframework.security: INFO

server:
  port: 8081

email:
  from: noreply@surfconext.nl
  magic-link-url: http://localhost:8081/saml/guest-idp/magic
  my-surfconext-url: http://localhost:3001

schac_home_organization: eduid.nl

cron:
  node-cron-job-responsible: True
  token-cleaner-expression: "0 0/15 * * * *"
  service-name-resolver-initial-delay-milliseconds: 1
  service-name-resolver-fixed-rate-milliseconds: 360_0000
  metadata-resolver-initial-delay-milliseconds: 1
  metadata-resolver-fixed-rate-milliseconds: 86_400_000
  metadata-resolver-url: "classpath:/metadata/idps-metadata.xml"

metadata_sp_url: "classpath:/metadata/sp-names.json"

mongodb_db: surf_id_test
base_domain: test2.surfconext.nl
saml_metadata_base_path: http://localhost:8081
base_path: http://localhost:8081
continue_after_login_url: http://localhost:8081/saml/guest-idp/continue
idp_redirect_url: http://localhost:3000
rp_id: localhost
rp_origin: http://localhost:3000
sp_redirect_url: http://localhost:3001
sp_entity_id: https://engine.test2.surfconext.nl/authentication/sp/metadata, https://engine.test.surfconext.nl/authentication/sp/metadata
sp_entity_metadata_url: https://engine.test2.surfconext.nl/authentication/sp/metadata, https://engine.test.surfconext.nl/authentication/sp/metadata
onegini_entity_id: http://mock-idp
guest_idp_entity_id: https://localhost.surf.id
my_conext_url: https://my.test2.surfconext.nl
domain: eduid.nl

feature:
  webauthn: True
  warning_educational_email_domain: True
  # Show / hide the connections page in the mijn GUI
  connections: True
  use_deny_allow_list:
    allow_enabled: False
    allow_location: "classpath:/deny-allow/allowed.json"

secure_cookie: false
idp_entity_id: https://localhost.surf.id
private_key_path: classpath:/myconext.pem
certificate_path: classpath:/myconext.crt

remember_me_max_age_seconds: 15_768_000
email_guessing_sleep_millis: 500

attribute_aggregation:
  user: aa
  password: secret

attribute_manipulation:
  user: oidcng
  password: secret

oidc-token-api:
  token-url: https://connect.test2.surfconext.nl/tokens
  user: eduid
  password: secret
  enabled: true

oidc:
  client-id: myconext.rp.localhost
  secret: secret
  idp-flow-redirect-url: http://localhost:8081/myconext/api/idp/oidc/redirect
  sp-flow-redirect-url: http://localhost:8081/myconext/api/sp/oidc/redirect
  base-url: https://connect.test2.surfconext.nl
  expiry-duration-days-non-validated: 180
  expiry-duration-days-validated: 2190

account_linking_context_class_ref:
  linked_institution: https://eduid.nl/trust/linked-institution
  validate_names: https://eduid.nl/trust/validate-names
  affiliation_student: https://eduid.nl/trust/affiliation-student

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/${mongodb_db}
      auto-index-creation: false
  mail:
    host: localhost
    port: 3025

management:
  health:
    mail:
      enabled: false
  info:
    git:
      mode: full

