logging:
  config: classpath:logback.xml
  level:
    myconext: INFO
    tiqr.org: INFO
    org.springframework.data.mongodb: WARN
    org.springframework.data.convert: WARN
    org.springframework.security: WARN
server:
  port: 8081
  error:
    path: "/error"

email:
  from: noreply@surfconext.nl
  magic-link-url: http://localhost:8081/saml/guest-idp/magic
  my-surfconext-url: http://localhost:3001
#  mail-templates-directory: file://opt/build/main/resources/mail_templates
  mail-templates-directory: classpath:mail_templates

schac_home_organization: eduid.nl

cron:
  node-cron-job-responsible: True
  token-cleaner-expression: "0 0/15 * * * *"
  service-name-resolver-initial-delay-milliseconds: 15000
  service-name-resolver-fixed-rate-milliseconds: 43_200_000
  metadata-resolver-initial-delay-milliseconds: 1
  metadata-resolver-fixed-rate-milliseconds: 86_400_000
  metadata-resolver-url: "classpath:/metadata/idps-metadata.xml"
  geo-location-refresh: "0 1 1 * * ?"

manage:
  username: myconext
  password: secret
  base_url: https://manage.test2.surfconext.nl

mongodb_db: surf_id_test
base_domain: test2.surfconext.nl
saml_metadata_base_path: http://localhost:8081
base_path: http://localhost:8081
continue_after_login_url: http://localhost:8081/saml/guest-idp/continue
idp_redirect_url: http://localhost:3000
rp_id: localhost
rp_origin: http://localhost:3000
sp_redirect_url: http://localhost:3001
sp_entity_id: https://engine.test2.surfconext.nl/authentication/sp/metadata, https://engine.test.surfconext.nl/authentication/sp/metadata
sp_entity_metadata_url: https://engine.test2.surfconext.nl/authentication/sp/metadata, https://engine.test.surfconext.nl/authentication/sp/metadata
onegini_entity_id: http://mock-idp
guest_idp_entity_id: https://localhost.surf.id
my_conext_url: https://my.test2.surfconext.nl
domain: eduid.nl
mijn_eduid_entity_id: http://mijn.localhost/shibboleth

feature:
  webauthn: True
  warning_educational_email_domain: True
  # Show / hide the connections page in the mijn GUI
  connections: True
  # Do we allow the account linking to take place with the accounting IdP, e.g. add extra button in IdP link screen
  use_external_validation: True
  # Do we deny emails that are known Disposable Email Providers
  deny_disposable_email_providers: True
  # Do we allow for multiple linked (institutional) accounts? Not yet implemented
  # multiple_linked_account: False
  use_deny_allow_list:
    allow_enabled: False
    allow_location: "classpath:/deny-allow/allowed.json"
  # Do we allow the create-from-institution flow
  create_eduid_institution_enabled: True
  # Do we show the landing page for the create-from-institution flow
  create_eduid_institution_landing: True

secure_cookie: false
idp_entity_id: https://localhost.surf.id
private_key_path: classpath:/myconext.pem
certificate_path: classpath:/myconext.crt

remember_me_max_age_seconds: 15_768_000
sso_mfa_duration_seconds: 900
nudge_eduid_app_days: 7
remember_me_question_asked_days: 30
email_guessing_sleep_millis: 500
email_spam_threshold_seconds: 15

sms:
  url: "http://localhost:8081/sms"
  bearer: "secret"

tiqr_configuration: "classpath:/tiqr.configuration.yml"

attribute_aggregation:
  user: aa
  password: secret

attribute_manipulation:
  user: oidcng
  password: secret

oidc-token-api:
  token-url: https://connect.test2.surfconext.nl/tokens
  user: eduid
  password: secret
  enabled: true

oidc:
  client-id: myconext.rp.localhost
  secret: secret
  idp-flow-redirect-url: http://localhost:8081/myconext/api/idp/oidc/redirect
  sp-flow-redirect-url: http://localhost:8081/myconext/api/sp/oidc/redirect
  sp-create-from-institution-redirect-url: http://localhost:8081/myconext/api/sp/create-from-institution/oidc-redirect
  base-url: https://connect.test2.surfconext.nl

linked_accounts:
  # The duration that not name-validated linked accounts are valid - note that they are not removed and will be used for EPPN Pseudonymisation
  expiry-duration-days-non-validated: 180
  # The duration after which linked accounts are removed
  removal-duration-days-validated: 2190

account_linking_context_class_ref:
  linked_institution: https://eduid.nl/trust/linked-institution
  validate_names: https://eduid.nl/trust/validate-names
  affiliation_student: https://eduid.nl/trust/affiliation-student
  profile_mfa: https://refeds.org/profile/mfa

account_linking:
  idp_external_validation_entity_id: http://mock-idp
  myconext_sp_entity_id: https://mijn.test2.eduid.nl/shibboleth

eduid_api:
#  oidcng_introspection_uri: http://localhost:8098/introspect
  oidcng_introspection_uri: https://connect.test2.surfconext/nl/oidc/introspect
  oidcng_client_id: myconext.local.rs
  oidcng_secret: secret

geo_location:
  license_key: lb53kEx9iVCuBcnV
  external_url: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key={license_key}&suffix=tar.gz"
  download_directory: "/var/tmp/geo2lite"

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/${mongodb_db}
      auto-index-creation: false
  mail:
    host: localhost
    port: 3025

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: "/internal"
  endpoint:
    info:
      enabled: true
  info:
    git:
      mode: full
