logging:
  level:
    org.springframework.data.mongodb: INFO
    org.springframework.data.convert: ERROR
    org.springframework.security: INFO

server:
  port: 8081

email:
  from: noreply@surfconext.nl
  magic-link-url: http://localhost:8081/saml/guest-idp/magic
  my-surfconext-url: http://localhost:3001

schac_home_organization: eduid.nl

cron:
  node-cron-job-responsible: True
  token-cleaner-expression: "0 0/15 * * * *"

metadata_sp_url: https://metadata.test.surfconext.nl/sp-names.json

mongodb_db: surf_id_test
base_domain: test2.surfconext.nl
base_path: http://localhost:8081
idp_redirect_url: http://localhost:3000
sp_redirect_url: http://localhost:3001
sp_entity_id: https://engine.test2.surfconext.nl/authentication/sp/metadata, https://engine.test.surfconext.nl/authentication/sp/metadata
sp_entity_metadata_url: https://engine.test2.surfconext.nl/authentication/sp/metadata, https://engine.test.surfconext.nl/authentication/sp/metadata
onegini_entity_id: http://mock-idp
guest_idp_entity_id: https://localhost.surf.id
my_conext_url: https://my.test2.surfconext.nl
domain: eduid.nl

secure_cookie: false
idp_entity_id: https://localhost.surf.id
private_key_path: classpath:/id_rsa
certificate_path: classpath:/id_rsa.pub
#private_key_path: classpath:/myconext.pem
#certificate_path: classpath:/myconext.crt

remember_me_max_age_seconds: 15_768_000
email_guessing_sleep_millis: 500

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/${mongodb_db}
  mail:
    host: localhost
    port: 3025

management:
  health:
    mail:
      enabled: false

  info:
    git:
      mode: full
