name: Deploy

on:
  push:
    tags:
      - "*"
#on:
#  create:
jobs:
  deployment:
#    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    environment: deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        distribution: 'adopt'
        server-id: openconext-releases
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Set up cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Deploy with Maven
      run: mvn -B --no-transfer-progress deploy -DskipTests --file pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.BUILD_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.BUILD_PASSWORD }}